"""add_strategy_execution_tables

Revision ID: 4ad58868baa7
Revises: 79636eecbe99
Create Date: 2026-07-10 17:08:15.987445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4ad58868baa7'
down_revision: Union[str, Sequence[str], None] = '79636eecbe99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False, comment='账户ID（关联 account_trading.trading_account）'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('total_pnl', sa.Float(), nullable=True),
    sa.Column('total_signals', sa.Integer(), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_strategy_id'), 'execution', ['strategy_id'], unique=False)
    op.create_table('risk_rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('rule_name', sa.String(length=100), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_rule_rule_type'), 'risk_rule', ['rule_type'], unique=False)
    op.create_index(op.f('ix_risk_rule_strategy_id'), 'risk_rule', ['strategy_id'], unique=False)
    op.create_table('execution_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['execution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_log_execution_id'), 'execution_log', ['execution_id'], unique=False)
    op.create_table('execution_signal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('symbol_name', sa.String(length=50), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('signal_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('risk_passed', sa.Boolean(), nullable=True),
    sa.Column('risk_reason', sa.String(length=255), nullable=True),
    sa.Column('order_id', sa.String(length=64), nullable=True),
    sa.Column('order_status', sa.String(length=20), nullable=True),
    sa.Column('filled_price', sa.Float(), nullable=True),
    sa.Column('filled_quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['execution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_signal_execution_id'), 'execution_signal', ['execution_id'], unique=False)
    op.create_index(op.f('ix_execution_signal_strategy_id'), 'execution_signal', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_execution_signal_symbol'), 'execution_signal', ['symbol'], unique=False)
    op.create_table('risk_alert',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=50), nullable=True),
    sa.Column('action_taken', sa.String(length=50), nullable=True),
    sa.Column('action_result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['execution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_alert_execution_id'), 'risk_alert', ['execution_id'], unique=False)
    op.alter_column('account_binding', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('account_binding', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('account_operation_step', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('account_operation_task', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('account_operation_task', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('account_runtime_status', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('account_runtime_status', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('backtest_balance_snapshot', 'total_asset',
               existing_type=mysql.DECIMAL(precision=20, scale=4),
               server_default='0',
               existing_comment='总资产',
               existing_nullable=False)
    op.alter_column('backtest_balance_snapshot', 'cash_balance',
               existing_type=mysql.DECIMAL(precision=20, scale=4),
               server_default='0',
               existing_comment='资金余额',
               existing_nullable=False)
    op.alter_column('backtest_balance_snapshot', 'available_cash',
               existing_type=mysql.DECIMAL(precision=20, scale=4),
               server_default='0',
               existing_comment='可用资金',
               existing_nullable=False)
    op.alter_column('backtest_balance_snapshot', 'withdrawable_cash',
               existing_type=mysql.DECIMAL(precision=20, scale=4),
               server_default='0',
               existing_comment='可取资金',
               existing_nullable=False)
    op.alter_column('backtest_balance_snapshot', 'frozen_cash',
               existing_type=mysql.DECIMAL(precision=20, scale=4),
               server_default='0',
               existing_comment='冻结资金',
               existing_nullable=False)
    op.alter_column('backtest_balance_snapshot', 'market_value',
               existing_type=mysql.DECIMAL(precision=20, scale=4),
               server_default='0',
               existing_comment='股票持仓市值',
               existing_nullable=False)
    op.alter_column('backtest_balance_snapshot', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('backtest_cash_flow', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('backtest_order', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('backtest_order', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('backtest_order_status_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('backtest_position_snapshot', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('backtest_run', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('backtest_run', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('backtest_trade', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('live_balance_snapshot', 'total_asset',
               existing_type=mysql.DECIMAL(precision=20, scale=4),
               server_default='0',
               existing_comment='总资产',
               existing_nullable=False)
    op.alter_column('live_balance_snapshot', 'cash_balance',
               existing_type=mysql.DECIMAL(precision=20, scale=4),
               server_default='0',
               existing_comment='资金余额',
               existing_nullable=False)
    op.alter_column('live_balance_snapshot', 'available_cash',
               existing_type=mysql.DECIMAL(precision=20, scale=4),
               server_default='0',
               existing_comment='可用资金',
               existing_nullable=False)
    op.alter_column('live_balance_snapshot', 'withdrawable_cash',
               existing_type=mysql.DECIMAL(precision=20, scale=4),
               server_default='0',
               existing_comment='可取资金',
               existing_nullable=False)
    op.alter_column('live_balance_snapshot', 'frozen_cash',
               existing_type=mysql.DECIMAL(precision=20, scale=4),
               server_default='0',
               existing_comment='冻结资金',
               existing_nullable=False)
    op.alter_column('live_balance_snapshot', 'market_value',
               existing_type=mysql.DECIMAL(precision=20, scale=4),
               server_default='0',
               existing_comment='股票持仓市值',
               existing_nullable=False)
    op.alter_column('live_balance_snapshot', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('live_cash_flow', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('live_order', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('live_order', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('live_order_status_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('live_position_snapshot', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('live_trade', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('paper_balance_snapshot', 'total_asset',
               existing_type=mysql.DECIMAL(precision=20, scale=4),
               server_default='0',
               existing_comment='总资产',
               existing_nullable=False)
    op.alter_column('paper_balance_snapshot', 'cash_balance',
               existing_type=mysql.DECIMAL(precision=20, scale=4),
               server_default='0',
               existing_comment='资金余额',
               existing_nullable=False)
    op.alter_column('paper_balance_snapshot', 'available_cash',
               existing_type=mysql.DECIMAL(precision=20, scale=4),
               server_default='0',
               existing_comment='可用资金',
               existing_nullable=False)
    op.alter_column('paper_balance_snapshot', 'withdrawable_cash',
               existing_type=mysql.DECIMAL(precision=20, scale=4),
               server_default='0',
               existing_comment='可取资金',
               existing_nullable=False)
    op.alter_column('paper_balance_snapshot', 'frozen_cash',
               existing_type=mysql.DECIMAL(precision=20, scale=4),
               server_default='0',
               existing_comment='冻结资金',
               existing_nullable=False)
    op.alter_column('paper_balance_snapshot', 'market_value',
               existing_type=mysql.DECIMAL(precision=20, scale=4),
               server_default='0',
               existing_comment='股票持仓市值',
               existing_nullable=False)
    op.alter_column('paper_balance_snapshot', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('paper_cash_flow', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('paper_order', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('paper_order', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('paper_order_status_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('paper_position_snapshot', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('paper_simulation_run', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('paper_simulation_run', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('paper_trade', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('review_drawdown_curve', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('review_equity_curve', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('review_metric_snapshot', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('review_session', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('review_session', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('review_suggestion', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('review_trade_item', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('trading_account', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('trading_account', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 禁用外键检查以避免外键约束报错
    op.execute("SET FOREIGN_KEY_CHECKS = 0")

    # 按照依赖关系逆序删除表（使用 DROP TABLE IF EXISTS）
    tables_to_drop = [
        'risk_alert',
        'execution_signal',
        'execution_log',
        'risk_rule',
        'execution',
    ]

    for table in tables_to_drop:
        op.execute(f"DROP TABLE IF EXISTS {table}")

    # 恢复外键检查
    op.execute("SET FOREIGN_KEY_CHECKS = 1")
    # ### end Alembic commands ###
