"""baseline: strategy_engine initial schema

Revision ID: 79636eecbe99
Revises:
Create Date: 2026-07-07 07:36:26.603969

本 baseline 涵盖全部 6 个模块的 schema（首次建立 alembic 治理）。
upgrade() 末尾追加 4 个 strategy_engine 内置策略的 INSERT。
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79636eecbe99'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ============================================================
# 内置策略初始数据（与 strategy_engine/builtin/*.py 对齐）
# ============================================================

# 延迟 import 避免在模块顶层产生循环依赖
def _load_builtin_strategy_codes() -> dict:
    """从 strategy_engine.builtin 加载 4 个内置策略的 Python 源码。"""
    from strategy_engine.builtin import (
        BOLLINGER_CODE,
        DOUBLE_MA_CODE,
        MACD_CODE,
        RSI_CODE,
    )
    return {
        "DOUBLE_MA": ("双均线交叉", "trend", DOUBLE_MA_CODE,
                      '{"short_window": 5, "long_window": 10, "buy_ratio": 0.95}',
                      '短期均线上穿长期均线买入，下穿卖出'),
        "RSI_REVERSAL": ("RSI 超买超卖", "mean_reversion", RSI_CODE,
                          '{"period": 14, "oversold": 30, "overbought": 70, "buy_ratio": 0.5}',
                          'RSI 低于 30 买入，高于 70 卖出'),
        "BOLLINGER_BREAK": ("布林带突破", "trend", BOLLINGER_CODE,
                             '{"period": 20, "std_dev": 2.0, "buy_ratio": 0.9}',
                             '价格突破布林带上/下轨'),
        "MACD_CROSS": ("MACD 金叉死叉", "trend", MACD_CODE,
                        '{"fast": 12, "slow": 26, "signal": 9, "buy_ratio": 0.9}',
                        'MACD 金叉买入，死叉卖出'),
    }


def _insert_builtin_strategies() -> None:
    """把 4 个内置策略 INSERT 到 strategy 表。"""
    from datetime import datetime

    codes = _load_builtin_strategy_codes()
    strategy_tbl = sa.table(
        "strategy",
        sa.column("code", sa.String),
        sa.column("name", sa.String),
        sa.column("strategy_type", sa.String),
        sa.column("description", sa.String),
        sa.column("status", sa.String),
        sa.column("version", sa.String),
        sa.column("code_content", sa.Text),
        sa.column("parameters", sa.JSON),
        sa.column("tags", sa.JSON),
        sa.column("author", sa.String),
        sa.column("is_default", sa.Boolean),
        sa.column("created_at", sa.DateTime),
        sa.column("updated_at", sa.DateTime),
    )
    now = datetime.now()
    rows = []
    for code, (name, stype, code_content, params_json, desc) in codes.items():
        import json
        try:
            params = json.loads(params_json) if isinstance(params_json, str) else params_json
        except Exception:
            params = {}
        rows.append({
            "code": code,
            "name": name,
            "strategy_type": stype,
            "description": desc,
            "status": "active",
            "version": "1.0.0",
            "code_content": code_content,
            "parameters": params,
            "tags": ["builtin", stype],
            "author": "system",
            "is_default": code == "DOUBLE_MA",
            "created_at": now,
            "updated_at": now,
        })
    op.bulk_insert(strategy_tbl, rows)


def _delete_builtin_strategies() -> None:
    """downgrade 时按 code 删除内置策略。

    codes 来自内部常量（不可注入），用字符串拼接 SQL 是安全的。
    如果表不存在则跳过（downgrade 到 base 时表可能还未创建）。
    """
    codes = list(_load_builtin_strategy_codes().keys())
    codes_str = ",".join(f"'{c}'" for c in codes)

    # 检查 strategy 表是否存在
    conn = op.get_bind()
    result = conn.execute(sa.text(
        "SELECT COUNT(*) FROM information_schema.tables "
        "WHERE table_schema = DATABASE() AND table_name = 'strategy'"
    ))
    if result.scalar() == 0:
        return  # 表不存在，跳过删除

    # 先删 strategy_version（如果存在）
    result = conn.execute(sa.text(
        "SELECT COUNT(*) FROM information_schema.tables "
        "WHERE table_schema = DATABASE() AND table_name = 'strategy_version'"
    ))
    if result.scalar() > 0:
        op.execute(sa.text(
            f"DELETE FROM strategy_version WHERE strategy_id IN "
            f"(SELECT id FROM strategy WHERE code IN ({codes_str}))"
        ))

    # 再删 strategy
    op.execute(sa.text(f"DELETE FROM strategy WHERE code IN ({codes_str})"))


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kline_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='股票代码'),
    sa.Column('timeframe', sa.String(length=10), nullable=False, comment='时间周期 1m/5m/1h/1d'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='K线时间戳'),
    sa.Column('open', sa.Float(), nullable=False, comment='开盘价'),
    sa.Column('high', sa.Float(), nullable=False, comment='最高价'),
    sa.Column('low', sa.Float(), nullable=False, comment='最低价'),
    sa.Column('close', sa.Float(), nullable=False, comment='收盘价'),
    sa.Column('volume', sa.Float(), nullable=False, comment='成交量'),
    sa.Column('turnover', sa.Float(), nullable=True, comment='成交额'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kline_data_symbol'), 'kline_data', ['symbol'], unique=False)
    op.create_table('realtime_quote',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='股票代码'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='股票名称'),
    sa.Column('last_price', sa.Float(), nullable=False, comment='最新价'),
    sa.Column('change', sa.Float(), nullable=False, comment='涨跌额'),
    sa.Column('change_pct', sa.Float(), nullable=False, comment='涨跌幅(%)'),
    sa.Column('open', sa.Float(), nullable=False, comment='开盘价'),
    sa.Column('high', sa.Float(), nullable=False, comment='最高价'),
    sa.Column('low', sa.Float(), nullable=False, comment='最低价'),
    sa.Column('volume', sa.Float(), nullable=False, comment='成交量'),
    sa.Column('turnover', sa.Float(), nullable=True, comment='成交额'),
    sa.Column('amplitude', sa.Float(), nullable=True, comment='振幅(%)'),
    sa.Column('market_cap', sa.Float(), nullable=True, comment='总市值'),
    sa.Column('float_market_cap', sa.Float(), nullable=True, comment='流通市值'),
    sa.Column('pe_ratio', sa.Float(), nullable=True, comment='市盈率'),
    sa.Column('pb_ratio', sa.Float(), nullable=True, comment='市净率'),
    sa.Column('buy1_price', sa.Float(), nullable=True, comment='买一价'),
    sa.Column('buy1_volume', sa.Float(), nullable=True, comment='买一量'),
    sa.Column('buy2_price', sa.Float(), nullable=True, comment='买二价'),
    sa.Column('buy2_volume', sa.Float(), nullable=True, comment='买二量'),
    sa.Column('buy3_price', sa.Float(), nullable=True, comment='买三价'),
    sa.Column('buy3_volume', sa.Float(), nullable=True, comment='买三量'),
    sa.Column('buy4_price', sa.Float(), nullable=True, comment='买四价'),
    sa.Column('buy4_volume', sa.Float(), nullable=True, comment='买四量'),
    sa.Column('buy5_price', sa.Float(), nullable=True, comment='买五价'),
    sa.Column('buy5_volume', sa.Float(), nullable=True, comment='买五量'),
    sa.Column('sell1_price', sa.Float(), nullable=True, comment='卖一价'),
    sa.Column('sell1_volume', sa.Float(), nullable=True, comment='卖一量'),
    sa.Column('sell2_price', sa.Float(), nullable=True, comment='卖二价'),
    sa.Column('sell2_volume', sa.Float(), nullable=True, comment='卖二量'),
    sa.Column('sell3_price', sa.Float(), nullable=True, comment='卖三价'),
    sa.Column('sell3_volume', sa.Float(), nullable=True, comment='卖三量'),
    sa.Column('sell4_price', sa.Float(), nullable=True, comment='卖四价'),
    sa.Column('sell4_volume', sa.Float(), nullable=True, comment='卖四量'),
    sa.Column('sell5_price', sa.Float(), nullable=True, comment='卖五价'),
    sa.Column('sell5_volume', sa.Float(), nullable=True, comment='卖五量'),
    sa.Column('timestamp', sa.DateTime(), nullable=False, comment='数据时间戳'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_realtime_quote_symbol'), 'realtime_quote', ['symbol'], unique=True)
    op.create_table('replay_bar',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='bar记录ID'),
    sa.Column('session_id', sa.BigInteger(), nullable=False, comment='关联回测会话ID'),
    sa.Column('bar_time', sa.String(length=10), nullable=False, comment='交易日期，格式 YYYY-MM-DD'),
    sa.Column('open', sa.Float(), nullable=False, comment='开盘价'),
    sa.Column('high', sa.Float(), nullable=False, comment='最高价'),
    sa.Column('low', sa.Float(), nullable=False, comment='最低价'),
    sa.Column('close', sa.Float(), nullable=False, comment='收盘价'),
    sa.Column('volume', sa.BigInteger(), nullable=False, comment='成交量（股）'),
    sa.Column('amount', sa.Float(), nullable=False, comment='成交额（元）'),
    sa.Column('benchmark_close', sa.Float(), nullable=False, comment='基准收盘价（如沪深300），用于计算Alpha/Beta/信息率/基准收益'),
    sa.Column('signal', sa.String(length=10), nullable=True, comment='触发的信号：buy/sell/None'),
    sa.Column('signal_reason', sa.String(length=100), nullable=True, comment='信号触发原因，如 均线金叉/RSI超卖'),
    sa.Column('cash', sa.Float(), nullable=False, comment='现金余额'),
    sa.Column('total_assets', sa.Float(), nullable=False, comment='总资产 = cash + sum(持仓市值)，最核心字段，几乎所有指标从它派生'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replay_bar_session_id'), 'replay_bar', ['session_id'], unique=False)
    op.create_index('ix_replay_bar_session_time', 'replay_bar', ['session_id', 'bar_time'], unique=True)
    op.create_table('replay_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='日志ID'),
    sa.Column('session_id', sa.BigInteger(), nullable=False, comment='关联回测会话ID'),
    sa.Column('bar_time', sa.String(length=10), nullable=False, comment='日志产生的交易日，格式 YYYY-MM-DD，关联 replay_bar'),
    sa.Column('level', sa.String(length=10), nullable=False, comment='日志级别：info/warn/error'),
    sa.Column('message', sa.Text(), nullable=False, comment='日志内容，如 [TRADE] 买入 000001.SZ 28400股 @10.53'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replay_log_session_id'), 'replay_log', ['session_id'], unique=False)
    op.create_index('ix_replay_log_session_time', 'replay_log', ['session_id', 'bar_time'], unique=False)
    op.create_table('replay_order',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='订单ID'),
    sa.Column('session_id', sa.BigInteger(), nullable=False, comment='关联回测会话ID'),
    sa.Column('bar_time', sa.String(length=10), nullable=False, comment='成交日期，格式 YYYY-MM-DD，关联 replay_bar'),
    sa.Column('side', sa.String(length=4), nullable=False, comment='交易方向：buy/sell'),
    sa.Column('price', sa.Float(), nullable=False, comment='成交价格（每股），回测中通常取当bar收盘价'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='成交数量（股数），由策略模块内部仓位管理决定'),
    sa.Column('amount', sa.Float(), nullable=False, comment='成交金额 = price × quantity'),
    sa.Column('commission', sa.Float(), nullable=False, comment='手续费（券商佣金+印花税等交易成本）'),
    sa.Column('pnl', sa.Float(), nullable=False, comment='盈亏金额，卖出时为已实现盈亏，买入时为0；计算方式：(卖价-买均价)×数量-双向手续费'),
    sa.Column('signal', sa.String(length=100), nullable=True, comment='触发信号名称，如 均线金叉/RSI超卖'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replay_order_session_id'), 'replay_order', ['session_id'], unique=False)
    op.create_index('ix_replay_order_session_time', 'replay_order', ['session_id', 'bar_time'], unique=False)
    op.create_table('replay_position',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='持仓记录ID'),
    sa.Column('session_id', sa.BigInteger(), nullable=False, comment='关联回测会话ID'),
    sa.Column('bar_time', sa.String(length=10), nullable=False, comment='交易日，格式 YYYY-MM-DD，关联 replay_bar'),
    sa.Column('stock_code', sa.String(length=20), nullable=False, comment='股票代码，如 000001.SZ'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='持仓数量（股数）'),
    sa.Column('cost_price', sa.Float(), nullable=False, comment='成本价（买入均价）'),
    sa.Column('current_price', sa.Float(), nullable=False, comment='当前价格（当日收盘价）'),
    sa.Column('market_value', sa.Float(), nullable=False, comment='市值 = quantity × current_price'),
    sa.Column('floating_pnl', sa.Float(), nullable=False, comment='浮盈 = 市值 - (成本价×数量)，正数浮盈/负数浮亏'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replay_position_session_id'), 'replay_position', ['session_id'], unique=False)
    op.create_index('ix_replay_position_session_time', 'replay_position', ['session_id', 'bar_time'], unique=False)
    op.create_table('replay_session',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='会话ID，唯一标识一次回测'),
    sa.Column('stock_code', sa.String(length=20), nullable=False, comment='股票代码，如 000001.SZ'),
    sa.Column('strategy_id', sa.Integer(), nullable=False, comment='策略ID，关联策略模块'),
    sa.Column('strategy_name', sa.String(length=100), nullable=False, comment='策略名称，快照，防止策略改名后历史记录对不上'),
    sa.Column('account_id', sa.Integer(), nullable=False, comment='虚拟账户ID，关联账户模块'),
    sa.Column('timeframe', sa.String(length=10), nullable=False, comment='时间间隔，如 1d/1h/5m'),
    sa.Column('start_date', sa.String(length=10), nullable=False, comment='回测起始日期，格式 YYYY-MM-DD'),
    sa.Column('end_date', sa.String(length=10), nullable=False, comment='回测结束日期，格式 YYYY-MM-DD'),
    sa.Column('total_bars', sa.Integer(), nullable=False, comment='总bar数，即回测覆盖的交易时段数'),
    sa.Column('time_elapsed', sa.Float(), nullable=False, comment='回测耗时（秒）'),
    sa.Column('initial_capital', sa.Float(), nullable=False, comment='期初总资产'),
    sa.Column('final_capital', sa.Float(), nullable=False, comment='期末总资产'),
    sa.Column('total_return', sa.Float(), nullable=False, comment='策略总收益率 %'),
    sa.Column('benchmark_return', sa.Float(), nullable=False, comment='基准总收益率 %'),
    sa.Column('annual_return', sa.Float(), nullable=False, comment='年化收益率 %'),
    sa.Column('max_drawdown', sa.Float(), nullable=False, comment='最大回撤 %'),
    sa.Column('sharpe_ratio', sa.Float(), nullable=False, comment='夏普比率'),
    sa.Column('sortino_ratio', sa.Float(), nullable=False, comment='索提诺比率'),
    sa.Column('alpha', sa.Float(), nullable=False, comment='Alpha，策略超额收益中无法被市场解释的部分'),
    sa.Column('beta', sa.Float(), nullable=False, comment='Beta，策略收益对市场收益的敏感度'),
    sa.Column('information_ratio', sa.Float(), nullable=False, comment='信息率，超额收益的稳定性'),
    sa.Column('strategy_volatility', sa.Float(), nullable=False, comment='策略年化波动率'),
    sa.Column('benchmark_volatility', sa.Float(), nullable=False, comment='基准年化波动率'),
    sa.Column('win_rate', sa.Float(), nullable=False, comment='胜率 %'),
    sa.Column('profit_loss_ratio', sa.Float(), nullable=False, comment='盈亏比'),
    sa.Column('trade_count', sa.Integer(), nullable=False, comment='交易次数（一买一卖算一次）'),
    sa.Column('total_pnl', sa.Float(), nullable=False, comment='总盈亏金额'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sector_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sector_code', sa.String(length=50), nullable=False, comment='板块代码'),
    sa.Column('sector_name', sa.String(length=100), nullable=False, comment='板块名称'),
    sa.Column('market', sa.String(length=10), nullable=False, comment='市场类型'),
    sa.Column('stock_count', sa.Integer(), nullable=False, comment='成分股数量'),
    sa.Column('description', sa.Text(), nullable=True, comment='板块描述'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sector_info_sector_code'), 'sector_info', ['sector_code'], unique=True)
    op.create_table('stock_base_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='股票代码'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='股票名称'),
    sa.Column('market', sa.String(length=10), nullable=False, comment='市场类型 A/HK/US'),
    sa.Column('sector', sa.String(length=100), nullable=True, comment='所属行业板块'),
    sa.Column('IPO_date', sa.String(length=20), nullable=True, comment='上市日期'),
    sa.Column('total_shares', sa.Float(), nullable=True, comment='总股本(万股)'),
    sa.Column('float_shares', sa.Float(), nullable=True, comment='流通股本(万股)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态 active/suspended/delisted'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_base_info_symbol'), 'stock_base_info', ['symbol'], unique=True)
    op.create_table('strategy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False, comment='策略编码'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='策略名称'),
    sa.Column('strategy_type', sa.String(length=32), nullable=False, comment='策略类型：trend/mean_reversion/arbitrage/sentiment'),
    sa.Column('description', sa.Text(), nullable=True, comment='策略描述'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态：draft/active/archived'),
    sa.Column('version', sa.String(length=32), nullable=False, comment='当前版本号'),
    sa.Column('code_content', sa.Text(), nullable=True, comment='当前生效的 Python 策略代码'),
    sa.Column('parameters', sa.JSON(), nullable=True, comment='默认参数'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签数组'),
    sa.Column('author', sa.String(length=64), nullable=True, comment='创建者'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否默认策略'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uk_strategy_code')
    )
    op.create_index('idx_strategy_status', 'strategy', ['status'], unique=False)
    op.create_index('idx_strategy_type', 'strategy', ['strategy_type'], unique=False)
    op.create_table('strategy_version',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False, comment='关联 strategy.id'),
    sa.Column('version', sa.String(length=32), nullable=False, comment='版本号'),
    sa.Column('change_log', sa.Text(), nullable=True, comment='变更日志'),
    sa.Column('code_content', sa.Text(), nullable=True, comment='代码快照'),
    sa.Column('parameters', sa.JSON(), nullable=True, comment='参数快照'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='状态：active/historical'),
    sa.Column('backtest_result', sa.JSON(), nullable=True, comment='该版本的回测结果摘要'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'version', name='uk_strategy_version')
    )
    op.create_index('ix_sv_strategy', 'strategy_version', ['strategy_id'], unique=False)
    op.create_table('trading_account',
    sa.Column('account_code', sa.String(length=64), nullable=False, comment='系统账户编码'),
    sa.Column('account_name', sa.String(length=128), nullable=False, comment='账户展示名'),
    sa.Column('account_type', sa.String(length=16), nullable=False, comment='live/paper/backtest'),
    sa.Column('broker_name', sa.String(length=64), nullable=True, comment='券商或平台名称'),
    sa.Column('broker_account_no', sa.String(length=64), nullable=True, comment='资金账号'),
    sa.Column('shareholder_account', sa.String(length=64), nullable=True, comment='股东账号'),
    sa.Column('exchange', sa.String(length=16), nullable=True, comment='交易市场，如 SH/SZ/BJ'),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False, comment='active/inactive/archived'),
    sa.Column('is_default', sa.BigInteger(), server_default='0', nullable=False, comment='是否默认账户'),
    sa.Column('meta_json', sa.JSON(), nullable=True, comment='扩展信息'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_code', name='uk_trading_account_code'),
    comment='账户主档'
    )
    op.create_index('idx_trading_account_broker_account_no', 'trading_account', ['broker_account_no'], unique=False)
    op.create_index('idx_trading_account_type', 'trading_account', ['account_type'], unique=False)
    op.create_table('account_binding',
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='关联 trading_account.id'),
    sa.Column('binding_type', sa.String(length=32), nullable=False, comment='desktop/ths/webapi/mock'),
    sa.Column('client_path', sa.String(length=255), nullable=True, comment='桌面客户端路径'),
    sa.Column('client_identity', sa.String(length=128), nullable=True, comment='客户端唯一标识'),
    sa.Column('login_account_name', sa.String(length=128), nullable=True, comment='界面展示的登录名'),
    sa.Column('login_account_mask', sa.String(length=64), nullable=True, comment='脱敏账号'),
    sa.Column('is_active', sa.BigInteger(), server_default='1', nullable=False, comment='是否启用'),
    sa.Column('last_connected_at', sa.DateTime(), nullable=True, comment='最近连接时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['account_id'], ['trading_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'binding_type', 'client_identity', name='uk_account_binding'),
    comment='账户绑定关系'
    )
    op.create_index('idx_account_binding_account_id', 'account_binding', ['account_id'], unique=False)
    op.create_table('account_operation_task',
    sa.Column('task_no', sa.String(length=64), nullable=False, comment='任务编号'),
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='关联 trading_account.id'),
    sa.Column('account_type', sa.String(length=16), nullable=False, comment='live/paper/backtest'),
    sa.Column('operation_type', sa.String(length=32), nullable=False, comment='connect/sync/buy/sell/cancel/query_balance/query_positions/query_orders/query_trades/backtest_run'),
    sa.Column('request_json', sa.JSON(), nullable=True, comment='请求参数'),
    sa.Column('response_json', sa.JSON(), nullable=True, comment='响应结果'),
    sa.Column('status', sa.String(length=32), server_default='created', nullable=False, comment='created/running/success/failed/captcha_waiting/manual_intervention_required/timeout'),
    sa.Column('error_code', sa.String(length=64), nullable=True, comment='错误编码'),
    sa.Column('error_message', sa.String(length=255), nullable=True, comment='错误消息'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('finished_at', sa.DateTime(), nullable=True, comment='结束时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['account_id'], ['trading_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_no', name='uk_account_operation_task_no'),
    comment='账户操作任务'
    )
    op.create_index('idx_account_operation_task_account_id', 'account_operation_task', ['account_id'], unique=False)
    op.create_index('idx_account_operation_task_status', 'account_operation_task', ['status'], unique=False)
    op.create_index('idx_account_operation_task_type', 'account_operation_task', ['operation_type'], unique=False)
    op.create_table('account_runtime_status',
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='关联 trading_account.id'),
    sa.Column('is_connected', sa.BigInteger(), server_default='0', nullable=False, comment='是否已连接'),
    sa.Column('is_ready', sa.BigInteger(), server_default='0', nullable=False, comment='是否可交易'),
    sa.Column('current_source', sa.String(length=16), nullable=True, comment='当前数据来源 live/paper/backtest'),
    sa.Column('window_title', sa.String(length=255), nullable=True, comment='交易客户端窗口标题'),
    sa.Column('window_class', sa.String(length=255), nullable=True, comment='交易客户端窗口类名'),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True, comment='最近同步时间'),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=True, comment='最近心跳时间'),
    sa.Column('last_error_code', sa.String(length=64), nullable=True, comment='最近错误编码'),
    sa.Column('last_error_message', sa.String(length=255), nullable=True, comment='最近错误消息'),
    sa.Column('detail_json', sa.JSON(), nullable=True, comment='扩展状态信息'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['account_id'], ['trading_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', name='uk_account_runtime_status_account_id'),
    comment='账户运行状态'
    )
    op.create_index('idx_account_runtime_status_account_id', 'account_runtime_status', ['account_id'], unique=False)
    op.create_table('backtest_run',
    sa.Column('run_id', sa.String(length=64), nullable=False, comment='回测运行批次ID'),
    sa.Column('account_id', sa.BigInteger(), nullable=True, comment='回测账户ID'),
    sa.Column('strategy_id', sa.String(length=64), nullable=False, comment='策略ID'),
    sa.Column('version_id', sa.String(length=64), nullable=True, comment='策略版本ID'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='回测开始日期'),
    sa.Column('end_date', sa.Date(), nullable=False, comment='回测结束日期'),
    sa.Column('initial_cash', sa.Numeric(precision=20, scale=4), nullable=False, comment='初始资金'),
    sa.Column('benchmark_symbol', sa.String(length=32), nullable=True, comment='基准指数代码'),
    sa.Column('frequency', sa.String(length=16), nullable=True, comment='回测频率'),
    sa.Column('params_json', sa.JSON(), nullable=True, comment='策略参数'),
    sa.Column('status', sa.String(length=16), server_default='created', nullable=False, comment='created/running/done/failed'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['account_id'], ['trading_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', name='uk_backtest_run_id'),
    comment='回测运行批次'
    )
    op.create_index('idx_backtest_date', 'backtest_run', ['start_date', 'end_date'], unique=False)
    op.create_index('idx_backtest_strategy', 'backtest_run', ['strategy_id', 'version_id'], unique=False)
    op.create_table('live_balance_snapshot',
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='实盘账户ID'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='交易日期'),
    sa.Column('snapshot_time', sa.DateTime(), nullable=False, comment='快照采集时间'),
    sa.Column('total_asset', sa.Numeric(precision=20, scale=4), server_default='0', nullable=False, comment='总资产'),
    sa.Column('cash_balance', sa.Numeric(precision=20, scale=4), server_default='0', nullable=False, comment='资金余额'),
    sa.Column('available_cash', sa.Numeric(precision=20, scale=4), server_default='0', nullable=False, comment='可用资金'),
    sa.Column('withdrawable_cash', sa.Numeric(precision=20, scale=4), server_default='0', nullable=False, comment='可取资金'),
    sa.Column('frozen_cash', sa.Numeric(precision=20, scale=4), server_default='0', nullable=False, comment='冻结资金'),
    sa.Column('market_value', sa.Numeric(precision=20, scale=4), server_default='0', nullable=False, comment='股票持仓市值'),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=4), nullable=True, comment='已实现盈亏'),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=4), nullable=True, comment='未实现盈亏'),
    sa.Column('source', sa.String(length=16), nullable=False, comment='数据来源 live/paper/backtest/replay/manual'),
    sa.Column('raw_json', sa.JSON(), nullable=True, comment='原始资金数据'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['account_id'], ['trading_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='实盘资金快照'
    )
    op.create_index('idx_live_balance_account_date', 'live_balance_snapshot', ['account_id', 'trade_date'], unique=False)
    op.create_index('idx_live_balance_snapshot_time', 'live_balance_snapshot', ['snapshot_time'], unique=False)
    op.create_table('live_cash_flow',
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='实盘账户ID'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='发生日期'),
    sa.Column('flow_type', sa.String(length=32), nullable=False, comment='流水类型：deposit/withdraw/freeze/unfreeze/trade_fee/tax/trade_cash'),
    sa.Column('ref_type', sa.String(length=32), nullable=True, comment='关联对象类型：order/trade/manual'),
    sa.Column('ref_id', sa.String(length=64), nullable=True, comment='关联对象ID或编号'),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False, comment='流水金额，收入为正，支出为负'),
    sa.Column('balance_after', sa.Numeric(precision=20, scale=4), nullable=True, comment='流水发生后的资金余额'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('raw_json', sa.JSON(), nullable=True, comment='原始流水数据'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['account_id'], ['trading_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='实盘现金流水'
    )
    op.create_index('idx_live_cash_account_date', 'live_cash_flow', ['account_id', 'trade_date'], unique=False)
    op.create_index('idx_live_cash_ref', 'live_cash_flow', ['ref_type', 'ref_id'], unique=False)
    op.create_table('live_order',
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='实盘账户ID'),
    sa.Column('strategy_id', sa.String(length=64), nullable=True, comment='策略ID'),
    sa.Column('version_id', sa.String(length=64), nullable=True, comment='策略版本ID'),
    sa.Column('run_id', sa.String(length=64), nullable=True, comment='策略运行批次ID'),
    sa.Column('signal_id', sa.String(length=64), nullable=True, comment='策略信号ID'),
    sa.Column('execution_id', sa.BigInteger(), nullable=True, comment='执行实例ID（关联 strategy_execution.execution）'),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True, comment='幂等键'),
    sa.Column('order_no', sa.String(length=64), nullable=True, comment='系统订单号'),
    sa.Column('broker_order_no', sa.String(length=64), nullable=True, comment='券商合同编号'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='委托交易日'),
    sa.Column('symbol', sa.String(length=32), nullable=False, comment='证券代码'),
    sa.Column('name', sa.String(length=128), nullable=True, comment='证券名称'),
    sa.Column('side', sa.String(length=8), nullable=False, comment='buy/sell'),
    sa.Column('order_type', sa.String(length=16), server_default='limit', nullable=False, comment='委托类型'),
    sa.Column('price', sa.Numeric(precision=20, scale=4), nullable=False, comment='委托价格'),
    sa.Column('quantity', sa.BigInteger(), nullable=False, comment='委托数量'),
    sa.Column('filled_quantity', sa.BigInteger(), server_default='0', nullable=False, comment='已成交数量'),
    sa.Column('canceled_quantity', sa.BigInteger(), server_default='0', nullable=False, comment='已撤数量'),
    sa.Column('avg_fill_price', sa.Numeric(precision=20, scale=4), nullable=True, comment='成交均价'),
    sa.Column('status', sa.String(length=24), nullable=False, comment='订单状态'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('source', sa.String(length=16), nullable=False, comment='数据来源'),
    sa.Column('submitted_at', sa.DateTime(), nullable=True, comment='提交时间'),
    sa.Column('accepted_at', sa.DateTime(), nullable=True, comment='接受时间'),
    sa.Column('canceled_at', sa.DateTime(), nullable=True, comment='撤单时间'),
    sa.Column('rejected_at', sa.DateTime(), nullable=True, comment='拒单时间'),
    sa.Column('raw_json', sa.JSON(), nullable=True, comment='原始委托数据'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['account_id'], ['trading_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_order_no', name='uk_live_broker_order_no'),
    sa.UniqueConstraint('order_no', name='uk_live_order_no'),
    comment='实盘委托'
    )
    op.create_index('idx_live_order_account_date', 'live_order', ['account_id', 'trade_date'], unique=False)
    op.create_index('idx_live_order_status', 'live_order', ['status'], unique=False)
    op.create_index('idx_live_order_strategy', 'live_order', ['strategy_id', 'version_id'], unique=False)
    op.create_index('idx_live_order_symbol', 'live_order', ['symbol'], unique=False)
    op.create_table('live_position_snapshot',
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='实盘账户ID'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='交易日期'),
    sa.Column('snapshot_time', sa.DateTime(), nullable=False, comment='快照采集时间'),
    sa.Column('symbol', sa.String(length=32), nullable=False, comment='证券代码'),
    sa.Column('name', sa.String(length=128), nullable=True, comment='证券名称'),
    sa.Column('exchange', sa.String(length=16), nullable=True, comment='交易所代码'),
    sa.Column('quantity', sa.BigInteger(), server_default='0', nullable=False, comment='当前持仓数量'),
    sa.Column('available_quantity', sa.BigInteger(), server_default='0', nullable=False, comment='可卖数量'),
    sa.Column('frozen_quantity', sa.BigInteger(), server_default='0', nullable=False, comment='冻结数量'),
    sa.Column('cost_price', sa.Numeric(precision=20, scale=4), nullable=True, comment='成本价'),
    sa.Column('last_price', sa.Numeric(precision=20, scale=4), nullable=True, comment='最新价'),
    sa.Column('market_value', sa.Numeric(precision=20, scale=4), nullable=True, comment='持仓市值'),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=4), nullable=True, comment='浮动盈亏'),
    sa.Column('pnl_ratio', sa.Numeric(precision=20, scale=6), nullable=True, comment='浮盈比例'),
    sa.Column('source', sa.String(length=16), nullable=False, comment='数据来源'),
    sa.Column('raw_json', sa.JSON(), nullable=True, comment='原始持仓数据'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['account_id'], ['trading_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'trade_date', 'symbol', name='uk_live_position'),
    comment='实盘持仓快照'
    )
    op.create_index('idx_live_position_symbol', 'live_position_snapshot', ['symbol'], unique=False)
    op.create_index('idx_live_position_time', 'live_position_snapshot', ['snapshot_time'], unique=False)
    op.create_table('paper_balance_snapshot',
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='模拟盘账户ID'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='交易日期'),
    sa.Column('snapshot_time', sa.DateTime(), nullable=False, comment='快照采集时间'),
    sa.Column('total_asset', sa.Numeric(precision=20, scale=4), server_default='0', nullable=False, comment='总资产'),
    sa.Column('cash_balance', sa.Numeric(precision=20, scale=4), server_default='0', nullable=False, comment='资金余额'),
    sa.Column('available_cash', sa.Numeric(precision=20, scale=4), server_default='0', nullable=False, comment='可用资金'),
    sa.Column('withdrawable_cash', sa.Numeric(precision=20, scale=4), server_default='0', nullable=False, comment='可取资金'),
    sa.Column('frozen_cash', sa.Numeric(precision=20, scale=4), server_default='0', nullable=False, comment='冻结资金'),
    sa.Column('market_value', sa.Numeric(precision=20, scale=4), server_default='0', nullable=False, comment='股票持仓市值'),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=4), nullable=True, comment='已实现盈亏'),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=4), nullable=True, comment='未实现盈亏'),
    sa.Column('source', sa.String(length=16), nullable=False, comment='数据来源'),
    sa.Column('raw_json', sa.JSON(), nullable=True, comment='原始资金数据'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['account_id'], ['trading_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='模拟盘资金快照'
    )
    op.create_index('idx_paper_balance_account_date', 'paper_balance_snapshot', ['account_id', 'trade_date'], unique=False)
    op.create_index('idx_paper_balance_snapshot_time', 'paper_balance_snapshot', ['snapshot_time'], unique=False)
    op.create_table('paper_cash_flow',
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='模拟盘账户ID'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='发生日期'),
    sa.Column('flow_type', sa.String(length=32), nullable=False, comment='流水类型：deposit/withdraw/freeze/unfreeze/trade_fee/tax/trade_cash'),
    sa.Column('ref_type', sa.String(length=32), nullable=True, comment='关联对象类型：order/trade/manual'),
    sa.Column('ref_id', sa.String(length=64), nullable=True, comment='关联对象ID或编号'),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False, comment='流水金额，收入为正，支出为负'),
    sa.Column('balance_after', sa.Numeric(precision=20, scale=4), nullable=True, comment='流水发生后的资金余额'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('raw_json', sa.JSON(), nullable=True, comment='原始流水数据'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['account_id'], ['trading_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='模拟盘现金流水'
    )
    op.create_index('idx_paper_cash_account_date', 'paper_cash_flow', ['account_id', 'trade_date'], unique=False)
    op.create_index('idx_paper_cash_ref', 'paper_cash_flow', ['ref_type', 'ref_id'], unique=False)
    op.create_table('paper_order',
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='模拟盘账户ID'),
    sa.Column('strategy_id', sa.String(length=64), nullable=True, comment='策略ID'),
    sa.Column('version_id', sa.String(length=64), nullable=True, comment='策略版本ID'),
    sa.Column('run_id', sa.String(length=64), nullable=True, comment='模拟运行批次ID'),
    sa.Column('signal_id', sa.String(length=64), nullable=True, comment='策略信号ID'),
    sa.Column('execution_id', sa.BigInteger(), nullable=True, comment='执行实例ID（关联 strategy_execution.execution）'),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True, comment='幂等键'),
    sa.Column('order_no', sa.String(length=64), nullable=True, comment='系统订单号'),
    sa.Column('broker_order_no', sa.String(length=64), nullable=True, comment='模拟合同编号'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='委托交易日'),
    sa.Column('symbol', sa.String(length=32), nullable=False, comment='证券代码'),
    sa.Column('name', sa.String(length=128), nullable=True, comment='证券名称'),
    sa.Column('side', sa.String(length=8), nullable=False, comment='buy/sell'),
    sa.Column('order_type', sa.String(length=16), server_default='limit', nullable=False, comment='委托类型'),
    sa.Column('price', sa.Numeric(precision=20, scale=4), nullable=False, comment='委托价格'),
    sa.Column('quantity', sa.BigInteger(), nullable=False, comment='委托数量'),
    sa.Column('filled_quantity', sa.BigInteger(), server_default='0', nullable=False, comment='已成交数量'),
    sa.Column('canceled_quantity', sa.BigInteger(), server_default='0', nullable=False, comment='已撤数量'),
    sa.Column('avg_fill_price', sa.Numeric(precision=20, scale=4), nullable=True, comment='成交均价'),
    sa.Column('status', sa.String(length=24), nullable=False, comment='订单状态'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('source', sa.String(length=16), nullable=False, comment='数据来源'),
    sa.Column('submitted_at', sa.DateTime(), nullable=True, comment='提交时间'),
    sa.Column('accepted_at', sa.DateTime(), nullable=True, comment='接受时间'),
    sa.Column('canceled_at', sa.DateTime(), nullable=True, comment='撤单时间'),
    sa.Column('rejected_at', sa.DateTime(), nullable=True, comment='拒单时间'),
    sa.Column('raw_json', sa.JSON(), nullable=True, comment='原始委托数据'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['account_id'], ['trading_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_order_no', name='uk_paper_broker_order_no'),
    sa.UniqueConstraint('order_no', name='uk_paper_order_no'),
    comment='模拟盘委托'
    )
    op.create_index('idx_paper_order_account_date', 'paper_order', ['account_id', 'trade_date'], unique=False)
    op.create_index('idx_paper_order_status', 'paper_order', ['status'], unique=False)
    op.create_index('idx_paper_order_strategy', 'paper_order', ['strategy_id', 'version_id'], unique=False)
    op.create_index('idx_paper_order_symbol', 'paper_order', ['symbol'], unique=False)
    op.create_table('paper_position_snapshot',
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='模拟盘账户ID'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='交易日期'),
    sa.Column('snapshot_time', sa.DateTime(), nullable=False, comment='快照采集时间'),
    sa.Column('symbol', sa.String(length=32), nullable=False, comment='证券代码'),
    sa.Column('name', sa.String(length=128), nullable=True, comment='证券名称'),
    sa.Column('exchange', sa.String(length=16), nullable=True, comment='交易所代码'),
    sa.Column('quantity', sa.BigInteger(), server_default='0', nullable=False, comment='当前持仓数量'),
    sa.Column('available_quantity', sa.BigInteger(), server_default='0', nullable=False, comment='可卖数量'),
    sa.Column('frozen_quantity', sa.BigInteger(), server_default='0', nullable=False, comment='冻结数量'),
    sa.Column('cost_price', sa.Numeric(precision=20, scale=4), nullable=True, comment='成本价'),
    sa.Column('last_price', sa.Numeric(precision=20, scale=4), nullable=True, comment='最新价'),
    sa.Column('market_value', sa.Numeric(precision=20, scale=4), nullable=True, comment='持仓市值'),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=4), nullable=True, comment='浮动盈亏'),
    sa.Column('pnl_ratio', sa.Numeric(precision=20, scale=6), nullable=True, comment='浮盈比例'),
    sa.Column('source', sa.String(length=16), nullable=False, comment='数据来源'),
    sa.Column('raw_json', sa.JSON(), nullable=True, comment='原始持仓数据'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['account_id'], ['trading_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'trade_date', 'symbol', name='uk_paper_position'),
    comment='模拟盘持仓快照'
    )
    op.create_index('idx_paper_position_symbol', 'paper_position_snapshot', ['symbol'], unique=False)
    op.create_index('idx_paper_position_time', 'paper_position_snapshot', ['snapshot_time'], unique=False)
    op.create_table('paper_simulation_run',
    sa.Column('run_id', sa.String(length=64), nullable=False, comment='模拟运行批次ID'),
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='模拟盘账户ID'),
    sa.Column('strategy_id', sa.String(length=64), nullable=True, comment='策略ID'),
    sa.Column('version_id', sa.String(length=64), nullable=True, comment='策略版本ID'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='模拟开始日期'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='模拟结束日期'),
    sa.Column('initial_cash', sa.Numeric(precision=20, scale=4), nullable=False, comment='初始资金'),
    sa.Column('benchmark_symbol', sa.String(length=32), nullable=True, comment='基准指数代码'),
    sa.Column('frequency', sa.String(length=16), nullable=True, comment='模拟频率，如 daily/1m/5m'),
    sa.Column('market_data_source', sa.String(length=64), nullable=True, comment='行情源'),
    sa.Column('matching_rule', sa.String(length=64), nullable=True, comment='撮合规则'),
    sa.Column('params_json', sa.JSON(), nullable=True, comment='模拟参数'),
    sa.Column('status', sa.String(length=16), server_default='created', nullable=False, comment='created/running/done/failed/canceled'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('finished_at', sa.DateTime(), nullable=True, comment='结束时间'),
    sa.Column('summary_json', sa.JSON(), nullable=True, comment='模拟结果摘要'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['account_id'], ['trading_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', name='uk_paper_simulation_run_id'),
    comment='模拟盘运行批次'
    )
    op.create_index('idx_paper_simulation_account', 'paper_simulation_run', ['account_id'], unique=False)
    op.create_index('idx_paper_simulation_date', 'paper_simulation_run', ['start_date', 'end_date'], unique=False)
    op.create_index('idx_paper_simulation_strategy', 'paper_simulation_run', ['strategy_id', 'version_id'], unique=False)
    op.create_table('review_session',
    sa.Column('session_code', sa.String(length=64), nullable=False, comment='复盘会话编码'),
    sa.Column('account_id', sa.BigInteger(), nullable=True, comment='关联账户ID'),
    sa.Column('strategy_id', sa.String(length=64), nullable=True, comment='策略ID'),
    sa.Column('version_id', sa.String(length=64), nullable=True, comment='策略版本ID'),
    sa.Column('account_type', sa.String(length=16), nullable=False, comment='复盘对象类型：live/paper/backtest'),
    sa.Column('source', sa.String(length=16), nullable=False, comment='数据来源：live/paper/backtest/replay'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='复盘开始日期'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='复盘结束日期'),
    sa.Column('benchmark_symbol', sa.String(length=32), nullable=True, comment='基准指数代码'),
    sa.Column('title', sa.String(length=128), nullable=True, comment='复盘标题'),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False, comment='draft/running/done/failed'),
    sa.Column('params_json', sa.JSON(), nullable=True, comment='复盘参数'),
    sa.Column('summary_json', sa.JSON(), nullable=True, comment='复盘摘要'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['account_id'], ['trading_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_code', name='uk_review_session_code'),
    comment='复盘会话'
    )
    op.create_index('idx_review_session_account', 'review_session', ['account_id'], unique=False)
    op.create_index('idx_review_session_status', 'review_session', ['status'], unique=False)
    op.create_index('idx_review_session_strategy', 'review_session', ['strategy_id', 'version_id'], unique=False)
    op.create_index('idx_review_session_type_date', 'review_session', ['account_type', 'start_date', 'end_date'], unique=False)
    op.create_table('account_operation_step',
    sa.Column('task_id', sa.BigInteger(), nullable=False, comment='关联 account_operation_task.id'),
    sa.Column('step_index', sa.BigInteger(), nullable=False, comment='步骤序号'),
    sa.Column('step_name', sa.String(length=64), nullable=False, comment='步骤名称'),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False, comment='pending/running/success/failed/skipped'),
    sa.Column('input_json', sa.JSON(), nullable=True, comment='步骤输入'),
    sa.Column('output_json', sa.JSON(), nullable=True, comment='步骤输出'),
    sa.Column('error_message', sa.String(length=255), nullable=True, comment='错误消息'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='开始时间'),
    sa.Column('finished_at', sa.DateTime(), nullable=True, comment='结束时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['task_id'], ['account_operation_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'step_index', name='uk_account_operation_step'),
    comment='账户操作步骤'
    )
    op.create_index('idx_account_operation_step_task_id', 'account_operation_step', ['task_id'], unique=False)
    op.create_table('backtest_balance_snapshot',
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='回测账户ID'),
    sa.Column('run_id', sa.String(length=64), nullable=False, comment='回测运行批次ID'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='交易日期'),
    sa.Column('snapshot_time', sa.DateTime(), nullable=False, comment='快照采集时间'),
    sa.Column('total_asset', sa.Numeric(precision=20, scale=4), server_default='0', nullable=False, comment='总资产'),
    sa.Column('cash_balance', sa.Numeric(precision=20, scale=4), server_default='0', nullable=False, comment='资金余额'),
    sa.Column('available_cash', sa.Numeric(precision=20, scale=4), server_default='0', nullable=False, comment='可用资金'),
    sa.Column('withdrawable_cash', sa.Numeric(precision=20, scale=4), server_default='0', nullable=False, comment='可取资金'),
    sa.Column('frozen_cash', sa.Numeric(precision=20, scale=4), server_default='0', nullable=False, comment='冻结资金'),
    sa.Column('market_value', sa.Numeric(precision=20, scale=4), server_default='0', nullable=False, comment='股票持仓市值'),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=4), nullable=True, comment='已实现盈亏'),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=4), nullable=True, comment='未实现盈亏'),
    sa.Column('source', sa.String(length=16), nullable=False, comment='数据来源'),
    sa.Column('raw_json', sa.JSON(), nullable=True, comment='原始资金数据'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['account_id'], ['trading_account.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_run.run_id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='回测资金快照'
    )
    op.create_index('idx_backtest_balance_account_date', 'backtest_balance_snapshot', ['account_id', 'trade_date'], unique=False)
    op.create_index('idx_backtest_balance_snapshot_time', 'backtest_balance_snapshot', ['snapshot_time'], unique=False)
    op.create_table('backtest_cash_flow',
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='回测账户ID'),
    sa.Column('run_id', sa.String(length=64), nullable=False, comment='回测运行批次ID'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='发生日期'),
    sa.Column('flow_type', sa.String(length=32), nullable=False, comment='流水类型：deposit/withdraw/freeze/unfreeze/trade_fee/tax/trade_cash'),
    sa.Column('ref_type', sa.String(length=32), nullable=True, comment='关联对象类型：order/trade/manual'),
    sa.Column('ref_id', sa.String(length=64), nullable=True, comment='关联对象ID或编号'),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False, comment='流水金额，收入为正，支出为负'),
    sa.Column('balance_after', sa.Numeric(precision=20, scale=4), nullable=True, comment='流水发生后的资金余额'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('raw_json', sa.JSON(), nullable=True, comment='原始流水数据'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['account_id'], ['trading_account.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_run.run_id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='回测现金流水'
    )
    op.create_index('idx_backtest_cash_account_date', 'backtest_cash_flow', ['account_id', 'trade_date'], unique=False)
    op.create_index('idx_backtest_cash_ref', 'backtest_cash_flow', ['ref_type', 'ref_id'], unique=False)
    op.create_index('idx_backtest_cash_run_date', 'backtest_cash_flow', ['run_id', 'trade_date'], unique=False)
    op.create_table('backtest_order',
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='回测账户ID'),
    sa.Column('run_id', sa.String(length=64), nullable=False, comment='回测运行批次ID'),
    sa.Column('strategy_id', sa.String(length=64), nullable=True, comment='策略ID'),
    sa.Column('version_id', sa.String(length=64), nullable=True, comment='策略版本ID'),
    sa.Column('signal_id', sa.String(length=64), nullable=True, comment='策略信号ID'),
    sa.Column('execution_id', sa.BigInteger(), nullable=True, comment='执行实例ID（关联 strategy_execution.execution）'),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True, comment='幂等键'),
    sa.Column('order_no', sa.String(length=64), nullable=True, comment='系统订单号'),
    sa.Column('broker_order_no', sa.String(length=64), nullable=True, comment='回测合同编号'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='委托交易日'),
    sa.Column('symbol', sa.String(length=32), nullable=False, comment='证券代码'),
    sa.Column('name', sa.String(length=128), nullable=True, comment='证券名称'),
    sa.Column('side', sa.String(length=8), nullable=False, comment='buy/sell'),
    sa.Column('order_type', sa.String(length=16), server_default='limit', nullable=False, comment='委托类型'),
    sa.Column('price', sa.Numeric(precision=20, scale=4), nullable=False, comment='委托价格'),
    sa.Column('quantity', sa.BigInteger(), nullable=False, comment='委托数量'),
    sa.Column('filled_quantity', sa.BigInteger(), server_default='0', nullable=False, comment='已成交数量'),
    sa.Column('canceled_quantity', sa.BigInteger(), server_default='0', nullable=False, comment='已撤数量'),
    sa.Column('avg_fill_price', sa.Numeric(precision=20, scale=4), nullable=True, comment='成交均价'),
    sa.Column('status', sa.String(length=24), nullable=False, comment='订单状态'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('source', sa.String(length=16), nullable=False, comment='数据来源'),
    sa.Column('submitted_at', sa.DateTime(), nullable=True, comment='提交时间'),
    sa.Column('accepted_at', sa.DateTime(), nullable=True, comment='接受时间'),
    sa.Column('canceled_at', sa.DateTime(), nullable=True, comment='撤单时间'),
    sa.Column('rejected_at', sa.DateTime(), nullable=True, comment='拒单时间'),
    sa.Column('raw_json', sa.JSON(), nullable=True, comment='原始委托数据'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['account_id'], ['trading_account.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_run.run_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_order_no', name='uk_backtest_broker_order_no'),
    sa.UniqueConstraint('order_no', name='uk_backtest_order_no'),
    comment='回测委托'
    )
    op.create_index('idx_backtest_order_account_date', 'backtest_order', ['account_id', 'trade_date'], unique=False)
    op.create_index('idx_backtest_order_status', 'backtest_order', ['status'], unique=False)
    op.create_index('idx_backtest_order_strategy', 'backtest_order', ['strategy_id', 'version_id'], unique=False)
    op.create_index('idx_backtest_order_symbol', 'backtest_order', ['symbol'], unique=False)
    op.create_table('backtest_position_snapshot',
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='回测账户ID'),
    sa.Column('run_id', sa.String(length=64), nullable=False, comment='回测运行批次ID'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='交易日期'),
    sa.Column('snapshot_time', sa.DateTime(), nullable=False, comment='快照采集时间'),
    sa.Column('symbol', sa.String(length=32), nullable=False, comment='证券代码'),
    sa.Column('name', sa.String(length=128), nullable=True, comment='证券名称'),
    sa.Column('exchange', sa.String(length=16), nullable=True, comment='交易所代码'),
    sa.Column('quantity', sa.BigInteger(), server_default='0', nullable=False, comment='当前持仓数量'),
    sa.Column('available_quantity', sa.BigInteger(), server_default='0', nullable=False, comment='可卖数量'),
    sa.Column('frozen_quantity', sa.BigInteger(), server_default='0', nullable=False, comment='冻结数量'),
    sa.Column('cost_price', sa.Numeric(precision=20, scale=4), nullable=True, comment='成本价'),
    sa.Column('last_price', sa.Numeric(precision=20, scale=4), nullable=True, comment='最新价'),
    sa.Column('market_value', sa.Numeric(precision=20, scale=4), nullable=True, comment='持仓市值'),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=4), nullable=True, comment='浮动盈亏'),
    sa.Column('pnl_ratio', sa.Numeric(precision=20, scale=6), nullable=True, comment='浮盈比例'),
    sa.Column('source', sa.String(length=16), nullable=False, comment='数据来源'),
    sa.Column('raw_json', sa.JSON(), nullable=True, comment='原始持仓数据'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['account_id'], ['trading_account.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_run.run_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'run_id', 'trade_date', 'symbol', name='uk_backtest_position'),
    comment='回测持仓快照'
    )
    op.create_index('idx_backtest_position_symbol', 'backtest_position_snapshot', ['symbol'], unique=False)
    op.create_index('idx_backtest_position_time', 'backtest_position_snapshot', ['snapshot_time'], unique=False)
    op.create_table('live_order_status_log',
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='实盘账户ID'),
    sa.Column('order_id', sa.BigInteger(), nullable=False, comment='关联 live_order.id'),
    sa.Column('broker_order_no', sa.String(length=64), nullable=True, comment='券商合同编号'),
    sa.Column('from_status', sa.String(length=24), nullable=True, comment='变化前状态'),
    sa.Column('to_status', sa.String(length=24), nullable=False, comment='变化后状态'),
    sa.Column('event_type', sa.String(length=32), nullable=False, comment='submit/accept/partial_fill/fill/cancel_request/cancel_success/reject/fail/sync_update'),
    sa.Column('event_source', sa.String(length=32), nullable=False, comment='ths_desktop/paper_engine/backtest_engine/manual_sync/strategy_engine'),
    sa.Column('event_time', sa.DateTime(), nullable=False, comment='事件时间'),
    sa.Column('detail_json', sa.JSON(), nullable=True, comment='事件详情'),
    sa.Column('message', sa.String(length=255), nullable=True, comment='事件说明'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['account_id'], ['trading_account.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['live_order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='实盘订单状态流水'
    )
    op.create_index('idx_live_order_status_log_account_id', 'live_order_status_log', ['account_id'], unique=False)
    op.create_index('idx_live_order_status_log_order_id', 'live_order_status_log', ['order_id'], unique=False)
    op.create_table('live_trade',
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='实盘账户ID'),
    sa.Column('order_id', sa.BigInteger(), nullable=True, comment='关联 live_order.id'),
    sa.Column('strategy_id', sa.String(length=64), nullable=True, comment='策略ID'),
    sa.Column('version_id', sa.String(length=64), nullable=True, comment='策略版本ID'),
    sa.Column('run_id', sa.String(length=64), nullable=True, comment='策略运行批次ID'),
    sa.Column('signal_id', sa.String(length=64), nullable=True, comment='策略信号ID'),
    sa.Column('trade_id', sa.String(length=64), nullable=True, comment='系统成交ID'),
    sa.Column('broker_trade_no', sa.String(length=64), nullable=True, comment='券商成交编号'),
    sa.Column('broker_order_no', sa.String(length=64), nullable=True, comment='券商合同编号'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='成交交易日'),
    sa.Column('traded_at', sa.DateTime(), nullable=False, comment='成交时间'),
    sa.Column('symbol', sa.String(length=32), nullable=False, comment='证券代码'),
    sa.Column('name', sa.String(length=128), nullable=True, comment='证券名称'),
    sa.Column('side', sa.String(length=8), nullable=False, comment='buy/sell'),
    sa.Column('price', sa.Numeric(precision=20, scale=4), nullable=False, comment='成交价格'),
    sa.Column('quantity', sa.BigInteger(), nullable=False, comment='成交数量'),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False, comment='成交金额'),
    sa.Column('commission', sa.Numeric(precision=20, scale=4), nullable=True, comment='佣金'),
    sa.Column('stamp_tax', sa.Numeric(precision=20, scale=4), nullable=True, comment='印花税'),
    sa.Column('transfer_fee', sa.Numeric(precision=20, scale=4), nullable=True, comment='过户费'),
    sa.Column('raw_json', sa.JSON(), nullable=True, comment='原始成交数据'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['account_id'], ['trading_account.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['live_order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id', name='uk_live_trade_id'),
    comment='实盘成交'
    )
    op.create_index('idx_live_trade_account_date', 'live_trade', ['account_id', 'trade_date'], unique=False)
    op.create_index('idx_live_trade_order_id', 'live_trade', ['order_id'], unique=False)
    op.create_index('idx_live_trade_symbol', 'live_trade', ['symbol'], unique=False)
    op.create_table('paper_order_status_log',
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='模拟盘账户ID'),
    sa.Column('order_id', sa.BigInteger(), nullable=False, comment='关联 paper_order.id'),
    sa.Column('broker_order_no', sa.String(length=64), nullable=True, comment='模拟合同编号'),
    sa.Column('from_status', sa.String(length=24), nullable=True, comment='变化前状态'),
    sa.Column('to_status', sa.String(length=24), nullable=False, comment='变化后状态'),
    sa.Column('event_type', sa.String(length=32), nullable=False, comment='submit/accept/partial_fill/fill/cancel_request/cancel_success/reject/fail/sync_update'),
    sa.Column('event_source', sa.String(length=32), nullable=False, comment='paper_engine/manual_sync/strategy_engine'),
    sa.Column('event_time', sa.DateTime(), nullable=False, comment='事件时间'),
    sa.Column('detail_json', sa.JSON(), nullable=True, comment='事件详情'),
    sa.Column('message', sa.String(length=255), nullable=True, comment='事件说明'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['account_id'], ['trading_account.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['paper_order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='模拟盘订单状态流水'
    )
    op.create_index('idx_paper_order_status_log_account_id', 'paper_order_status_log', ['account_id'], unique=False)
    op.create_index('idx_paper_order_status_log_order_id', 'paper_order_status_log', ['order_id'], unique=False)
    op.create_table('paper_trade',
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='模拟盘账户ID'),
    sa.Column('order_id', sa.BigInteger(), nullable=True, comment='关联 paper_order.id'),
    sa.Column('strategy_id', sa.String(length=64), nullable=True, comment='策略ID'),
    sa.Column('version_id', sa.String(length=64), nullable=True, comment='策略版本ID'),
    sa.Column('run_id', sa.String(length=64), nullable=True, comment='模拟运行批次ID'),
    sa.Column('signal_id', sa.String(length=64), nullable=True, comment='策略信号ID'),
    sa.Column('trade_id', sa.String(length=64), nullable=True, comment='系统成交ID'),
    sa.Column('broker_trade_no', sa.String(length=64), nullable=True, comment='模拟成交编号'),
    sa.Column('broker_order_no', sa.String(length=64), nullable=True, comment='模拟合同编号'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='成交交易日'),
    sa.Column('traded_at', sa.DateTime(), nullable=False, comment='成交时间'),
    sa.Column('symbol', sa.String(length=32), nullable=False, comment='证券代码'),
    sa.Column('name', sa.String(length=128), nullable=True, comment='证券名称'),
    sa.Column('side', sa.String(length=8), nullable=False, comment='buy/sell'),
    sa.Column('price', sa.Numeric(precision=20, scale=4), nullable=False, comment='成交价格'),
    sa.Column('quantity', sa.BigInteger(), nullable=False, comment='成交数量'),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False, comment='成交金额'),
    sa.Column('commission', sa.Numeric(precision=20, scale=4), nullable=True, comment='佣金'),
    sa.Column('stamp_tax', sa.Numeric(precision=20, scale=4), nullable=True, comment='印花税'),
    sa.Column('transfer_fee', sa.Numeric(precision=20, scale=4), nullable=True, comment='过户费'),
    sa.Column('raw_json', sa.JSON(), nullable=True, comment='原始成交数据'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['account_id'], ['trading_account.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['paper_order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id', name='uk_paper_trade_id'),
    comment='模拟盘成交'
    )
    op.create_index('idx_paper_trade_account_date', 'paper_trade', ['account_id', 'trade_date'], unique=False)
    op.create_index('idx_paper_trade_order_id', 'paper_trade', ['order_id'], unique=False)
    op.create_index('idx_paper_trade_symbol', 'paper_trade', ['symbol'], unique=False)
    op.create_table('review_drawdown_curve',
    sa.Column('session_id', sa.BigInteger(), nullable=False, comment='所属复盘会话ID'),
    sa.Column('curve_date', sa.Date(), nullable=False, comment='曲线日期'),
    sa.Column('curve_time', sa.DateTime(), nullable=True, comment='曲线时间点'),
    sa.Column('equity', sa.Numeric(precision=20, scale=8), nullable=False, comment='当前净值'),
    sa.Column('peak_equity', sa.Numeric(precision=20, scale=8), nullable=False, comment='历史峰值净值'),
    sa.Column('drawdown', sa.Numeric(precision=20, scale=8), nullable=False, comment='当前回撤'),
    sa.Column('drawdown_amount', sa.Numeric(precision=20, scale=4), nullable=True, comment='当前回撤金额'),
    sa.Column('peak_date', sa.Date(), nullable=True, comment='峰值日期'),
    sa.Column('detail_json', sa.JSON(), nullable=True, comment='回撤点扩展数据'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['session_id'], ['review_session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'curve_date', 'curve_time', name='uk_review_drawdown_point'),
    comment='复盘回撤曲线'
    )
    op.create_index('idx_review_drawdown_date', 'review_drawdown_curve', ['curve_date'], unique=False)
    op.create_index('idx_review_drawdown_session', 'review_drawdown_curve', ['session_id'], unique=False)
    op.create_table('review_equity_curve',
    sa.Column('session_id', sa.BigInteger(), nullable=False, comment='所属复盘会话ID'),
    sa.Column('curve_date', sa.Date(), nullable=False, comment='曲线日期'),
    sa.Column('curve_time', sa.DateTime(), nullable=True, comment='曲线时间点'),
    sa.Column('equity', sa.Numeric(precision=20, scale=8), nullable=False, comment='净值'),
    sa.Column('total_asset', sa.Numeric(precision=20, scale=4), nullable=True, comment='总资产'),
    sa.Column('cash_balance', sa.Numeric(precision=20, scale=4), nullable=True, comment='现金余额'),
    sa.Column('market_value', sa.Numeric(precision=20, scale=4), nullable=True, comment='持仓市值'),
    sa.Column('cumulative_return', sa.Numeric(precision=20, scale=8), nullable=True, comment='累计收益率'),
    sa.Column('benchmark_value', sa.Numeric(precision=20, scale=8), nullable=True, comment='基准净值'),
    sa.Column('detail_json', sa.JSON(), nullable=True, comment='曲线点扩展数据'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['session_id'], ['review_session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'curve_date', 'curve_time', name='uk_review_equity_point'),
    comment='复盘净值曲线'
    )
    op.create_index('idx_review_equity_date', 'review_equity_curve', ['curve_date'], unique=False)
    op.create_index('idx_review_equity_session', 'review_equity_curve', ['session_id'], unique=False)
    op.create_table('review_metric_snapshot',
    sa.Column('session_id', sa.BigInteger(), nullable=False, comment='所属复盘会话ID'),
    sa.Column('metric_key', sa.String(length=64), nullable=False, comment='指标编码'),
    sa.Column('metric_value', sa.Numeric(precision=20, scale=8), nullable=True, comment='数值型指标值'),
    sa.Column('metric_text', sa.String(length=255), nullable=True, comment='文本型指标值'),
    sa.Column('metric_unit', sa.String(length=32), nullable=True, comment='指标单位'),
    sa.Column('group_key', sa.String(length=64), nullable=True, comment='指标分组'),
    sa.Column('detail_json', sa.JSON(), nullable=True, comment='指标扩展详情'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['session_id'], ['review_session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'metric_key', name='uk_review_metric_session_key'),
    comment='复盘指标快照'
    )
    op.create_index('idx_review_metric_key', 'review_metric_snapshot', ['metric_key'], unique=False)
    op.create_index('idx_review_metric_session', 'review_metric_snapshot', ['session_id'], unique=False)
    op.create_table('review_suggestion',
    sa.Column('session_id', sa.BigInteger(), nullable=False, comment='所属复盘会话ID'),
    sa.Column('suggestion_type', sa.String(length=64), nullable=False, comment='建议类型：risk/position/entry/exit/parameter'),
    sa.Column('severity', sa.String(length=16), nullable=False, comment='严重程度：low/medium/high'),
    sa.Column('title', sa.String(length=128), nullable=False, comment='建议标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='建议正文'),
    sa.Column('evidence_json', sa.JSON(), nullable=True, comment='支撑证据'),
    sa.Column('status', sa.String(length=16), server_default='open', nullable=False, comment='open/accepted/rejected/resolved'),
    sa.Column('owner', sa.String(length=64), nullable=True, comment='建议负责人'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['session_id'], ['review_session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='复盘优化建议'
    )
    op.create_index('idx_review_suggestion_session', 'review_suggestion', ['session_id'], unique=False)
    op.create_index('idx_review_suggestion_severity', 'review_suggestion', ['severity'], unique=False)
    op.create_index('idx_review_suggestion_type', 'review_suggestion', ['suggestion_type'], unique=False)
    op.create_table('review_trade_item',
    sa.Column('session_id', sa.BigInteger(), nullable=False, comment='所属复盘会话ID'),
    sa.Column('account_id', sa.BigInteger(), nullable=True, comment='所属账户ID'),
    sa.Column('order_id', sa.BigInteger(), nullable=True, comment='来源委托ID'),
    sa.Column('trade_id', sa.String(length=64), nullable=True, comment='来源成交ID'),
    sa.Column('source', sa.String(length=16), nullable=False, comment='数据来源：live/paper/backtest/replay'),
    sa.Column('strategy_id', sa.String(length=64), nullable=True, comment='策略ID'),
    sa.Column('version_id', sa.String(length=64), nullable=True, comment='策略版本ID'),
    sa.Column('run_id', sa.String(length=64), nullable=True, comment='运行批次ID'),
    sa.Column('signal_id', sa.String(length=64), nullable=True, comment='策略信号ID'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='交易日期'),
    sa.Column('traded_at', sa.DateTime(), nullable=True, comment='成交时间'),
    sa.Column('symbol', sa.String(length=32), nullable=False, comment='证券代码'),
    sa.Column('name', sa.String(length=128), nullable=True, comment='证券名称'),
    sa.Column('side', sa.String(length=8), nullable=False, comment='buy/sell'),
    sa.Column('price', sa.Numeric(precision=20, scale=4), nullable=False, comment='成交价格'),
    sa.Column('quantity', sa.BigInteger(), nullable=False, comment='成交数量'),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False, comment='成交金额'),
    sa.Column('pnl', sa.Numeric(precision=20, scale=4), nullable=True, comment='该笔交易或交易对盈亏'),
    sa.Column('pnl_ratio', sa.Numeric(precision=20, scale=8), nullable=True, comment='盈亏比例'),
    sa.Column('holding_period_minutes', sa.BigInteger(), nullable=True, comment='持仓时长，单位分钟'),
    sa.Column('signal_tag', sa.String(length=64), nullable=True, comment='交易标签'),
    sa.Column('detail_json', sa.JSON(), nullable=True, comment='复盘明细扩展数据'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['account_id'], ['trading_account.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['review_session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='复盘交易明细'
    )
    op.create_index('idx_review_trade_account', 'review_trade_item', ['account_id'], unique=False)
    op.create_index('idx_review_trade_date', 'review_trade_item', ['trade_date'], unique=False)
    op.create_index('idx_review_trade_session', 'review_trade_item', ['session_id'], unique=False)
    op.create_index('idx_review_trade_strategy', 'review_trade_item', ['strategy_id', 'version_id'], unique=False)
    op.create_index('idx_review_trade_symbol', 'review_trade_item', ['symbol'], unique=False)
    op.create_table('backtest_order_status_log',
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='回测账户ID'),
    sa.Column('order_id', sa.BigInteger(), nullable=False, comment='关联 backtest_order.id'),
    sa.Column('run_id', sa.String(length=64), nullable=False, comment='回测运行批次ID'),
    sa.Column('broker_order_no', sa.String(length=64), nullable=True, comment='回测合同编号'),
    sa.Column('from_status', sa.String(length=24), nullable=True, comment='变化前状态'),
    sa.Column('to_status', sa.String(length=24), nullable=False, comment='变化后状态'),
    sa.Column('event_type', sa.String(length=32), nullable=False, comment='submit/accept/partial_fill/fill/cancel_request/cancel_success/reject/fail/sync_update'),
    sa.Column('event_source', sa.String(length=32), nullable=False, comment='backtest_engine/manual_sync/strategy_engine'),
    sa.Column('event_time', sa.DateTime(), nullable=False, comment='事件时间'),
    sa.Column('detail_json', sa.JSON(), nullable=True, comment='事件详情'),
    sa.Column('message', sa.String(length=255), nullable=True, comment='事件说明'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['account_id'], ['trading_account.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['backtest_order.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_run.run_id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='回测订单状态流水'
    )
    op.create_index('idx_backtest_order_status_log_account_id', 'backtest_order_status_log', ['account_id'], unique=False)
    op.create_index('idx_backtest_order_status_log_order_id', 'backtest_order_status_log', ['order_id'], unique=False)
    op.create_table('backtest_trade',
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='回测账户ID'),
    sa.Column('order_id', sa.BigInteger(), nullable=True, comment='关联 backtest_order.id'),
    sa.Column('run_id', sa.String(length=64), nullable=False, comment='回测运行批次ID'),
    sa.Column('strategy_id', sa.String(length=64), nullable=True, comment='策略ID'),
    sa.Column('version_id', sa.String(length=64), nullable=True, comment='策略版本ID'),
    sa.Column('signal_id', sa.String(length=64), nullable=True, comment='策略信号ID'),
    sa.Column('trade_id', sa.String(length=64), nullable=True, comment='系统成交ID'),
    sa.Column('broker_trade_no', sa.String(length=64), nullable=True, comment='回测成交编号'),
    sa.Column('broker_order_no', sa.String(length=64), nullable=True, comment='回测合同编号'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='成交交易日'),
    sa.Column('traded_at', sa.DateTime(), nullable=False, comment='成交时间'),
    sa.Column('symbol', sa.String(length=32), nullable=False, comment='证券代码'),
    sa.Column('name', sa.String(length=128), nullable=True, comment='证券名称'),
    sa.Column('side', sa.String(length=8), nullable=False, comment='buy/sell'),
    sa.Column('price', sa.Numeric(precision=20, scale=4), nullable=False, comment='成交价格'),
    sa.Column('quantity', sa.BigInteger(), nullable=False, comment='成交数量'),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False, comment='成交金额'),
    sa.Column('commission', sa.Numeric(precision=20, scale=4), nullable=True, comment='佣金'),
    sa.Column('stamp_tax', sa.Numeric(precision=20, scale=4), nullable=True, comment='印花税'),
    sa.Column('transfer_fee', sa.Numeric(precision=20, scale=4), nullable=True, comment='过户费'),
    sa.Column('raw_json', sa.JSON(), nullable=True, comment='原始成交数据'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['account_id'], ['trading_account.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['backtest_order.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_run.run_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id', name='uk_backtest_trade_id'),
    comment='回测成交'
    )
    op.create_index('idx_backtest_trade_account_date', 'backtest_trade', ['account_id', 'trade_date'], unique=False)
    op.create_index('idx_backtest_trade_order_id', 'backtest_trade', ['order_id'], unique=False)
    op.create_index('idx_backtest_trade_symbol', 'backtest_trade', ['symbol'], unique=False)
    # ### end Alembic commands ###

    # === 追加：4 个内置策略初始数据 ===
    _insert_builtin_strategies()


def downgrade() -> None:
    """Downgrade schema."""
    # === 先删除内置策略数据 ===
    _delete_builtin_strategies()

    # MySQL 8 在 DROP INDEX 时如果被 FK 引用会报错
    # 解决方案：禁用 FK 检查 + 使用 DROP TABLE IF EXISTS
    op.execute("SET FOREIGN_KEY_CHECKS = 0")

    # ### commands auto generated by Alembic - please adjust! ###
    # 使用 DROP TABLE IF EXISTS 避免表不存在时报错
    # 按照依赖关系逆序删除表
    tables_to_drop = [
        'backtest_trade',
        'backtest_order_status_log',
        'review_trade_item',
        'review_suggestion',
        'review_metric_snapshot',
        'review_equity_curve',
        'review_drawdown_curve',
        'paper_trade',
        'paper_order_status_log',
        'live_trade',
        'live_order_status_log',
        'backtest_position_snapshot',
        'backtest_order',
        'backtest_cash_flow',
        'backtest_balance_snapshot',
        'account_operation_step',
        'review_session',
        'paper_simulation_run',
        'paper_position_snapshot',
        'paper_order',
        'paper_cash_flow',
        'paper_balance_snapshot',
        'live_position_snapshot',
        'live_order',
        'live_cash_flow',
        'live_balance_snapshot',
        'backtest_run',
        'account_runtime_status',
        'account_operation_task',
        'account_binding',
        'trading_account',
        'strategy_version',
        'strategy',
        'stock_base_info',
        'sector_info',
        'replay_session',
        'replay_position',
        'replay_order',
        'replay_log',
        'replay_bar',
        'realtime_quote',
        'kline_data',
    ]

    for table in tables_to_drop:
        op.execute(f"DROP TABLE IF EXISTS {table}")
    # ### end Alembic commands ###

    op.execute("SET FOREIGN_KEY_CHECKS = 1")
